name: Deploy Kafka Migration System

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
        sudo systemctl start docker
        sudo docker --version
        docker-compose --version
        
    - name: Build and start containers
      run: |
        docker-compose build
        docker-compose up -d
        
    - name: Check running services
      run: |
        docker ps -a
        docker-compose ps
      continue-on-error: true
      
    - name: Verify Kafka
      run: |
        docker exec kafka kafka-topics --list --bootstrap-server kafka:9092
      continue-on-error: true
