name: Deploy Kafka Migration System

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker with Compose plugin
      run: |
        # Remove any existing Docker installations
        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
        
        # Install prerequisites
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg lsb-release
        
        # Add Docker's official GPG key
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        
        # Set up the repository
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        
        # Install Docker Engine with Compose plugin
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        
        # Create symbolic link for docker-compose compatibility
        sudo ln -s /usr/libexec/docker/cli-plugins/docker-compose /usr/bin/docker-compose
        
        # Verify installation
        sudo docker --version
        sudo docker compose version
        sudo docker-compose --version
        
        # Add current user to docker group (needs logout/login to take effect)
        sudo usermod -aG docker $USER
        
    - name: Build and start containers
      run: |
        sudo docker compose version
        sudo docker-compose build
        sudo docker-compose up -d
        
    - name: Check running services
      run: |
        sudo docker ps -a
        sudo docker-compose ps
      continue-on-error: true
      
    - name: Verify Kafka
      run: |
        sudo docker exec kafka kafka-topics --list --bootstrap-server kafka:9092
      continue-on-error: true
      
    - name: Show logs on failure
      if: failure()
      run: |
        sudo docker-compose logs
